In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt

In [2]:
conflict_data_ukr = pd.read_csv('../data/conflict_data/conflict_data_ukr.csv')
conflict_data_ukr.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,...,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
0,NaN,NaN,#date+year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#date+end,NaN,NaN,NaN,NaN,#affected+killed,NaN,NaN,NaN,NaN
1,147997.0,UKR-2014-1-14085-0,2014,1.0,Clear,1.0,13219.0,13219.0,Ukraine: Government,14085.0,...,2014-01-22 00:00:00.000,0.0,5.0,0.0,0.0,5,5.0,5.0,369.0,NaN
2,149221.0,UKR-2014-1-14085-1,2014,1.0,Clear,1.0,13219.0,13219.0,Ukraine: Government,14085.0,...,2014-01-27 00:00:00.000,0.0,0.0,0.0,1.0,1,1.0,1.0,369.0,NaN
3,149248.0,UKR-2014-1-14085-3,2014,1.0,Clear,1.0,13219.0,13219.0,Ukraine: Government,14085.0,...,2014-02-18 00:00:00.000,10.0,4.0,0.0,12.0,26,26.0,26.0,369.0,NaN
4,149249.0,UKR-2014-1-14085-4,2014,1.0,Clear,1.0,13219.0,13219.0,Ukraine: Government,14085.0,...,2014-02-20 00:00:00.000,0.0,0.0,0.0,2.0,2,2.0,2.0,369.0,NaN

In [3]:
ukraineconflict = pd.read_csv('../data/conflict_data/UkraineConflict.csv')
ukraineconflict.head()

,EVENT_ID_CNTY,EVENT_DATE,YEAR,TIME_PRECISION,DISORDER_TYPE,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,INTER1,...,LOCATION,LATITUDE,LONGITUDE,GEO_PRECISION,SOURCE,SOURCE_SCALE,NOTES,FATALITIES,TAGS,TIMESTAMP
0,ROU448,20-May-2019,2019,1,Political violence,Violence against civilians,Attack,Police Forces of Romania (2016-2019) Coast Guard,NaN,1,...,Coast of Constanta,44.156,28.948,2,Deschide; Hurriyet Daily; News.ro; CNN; TRT Haber,National-International,"On 20 May 2019, the Coast Guard of Romania fir...",0,NaN,1649875498
1,ROU1885,28-March-2022,2022,1,Strategic developments,Strategic developments,Disrupted weapons use,Military Forces of Romania (2021-),NaN,1,...,Coast of Constanta,44.156,28.948,1,Adevarul; G4media,National,"Defusal: On 28 March 2022, Romanian minesweepe...",0,NaN,1649184809
2,ROU1940,28-July-2022,2022,1,Demonstrations,Protests,Peaceful protest,Protesters (Romania),Greenpeace,6,...,Coast of Constanta,44.156,28.948,1,News.ro,National,"On 28 July 2022, Greenpeace activists proteste...",0,crowd size=no report,1659462993
3,ROU1945,31-July-2022,2022,1,Strategic developments,Strategic developments,Disrupted weapons use,Military Forces of Romania (2021-),NaN,1,...,Coast of Constanta,44.156,28.948,1,Digi24,National,"Defusal: On 31 July 2022, Romanian Naval Force...",0,NaN,1660055880
4,ROU1947,04-August-2022,2022,1,Demonstrations,Protests,Peaceful protest,Protesters (Romania),Greenpeace,6,...,Coast of Constanta,44.156,28.948,1,News.ro,National,"On 4 August 2022, Greenpeace activists protest...",0,crowd size=no report,1660055882

In [5]:
cumulative_loss_value = pd.read_csv('../data/losses/cummulative_loss_value.csv')
cumulative_loss_value.head()

,Unnamed: 0,date,aircraft,helicopter,tank,APC,field artillery,MRL,drone,naval ship,anti-aircraft warfare,military auto
0,0,2022-02,435000000,232000000,180000000,326400000,44400000,16800000,300000,20000000,25000000,23280000
1,1,2022-03,2025000000,1048000000,736800000,694000000,186600000,76800000,8300000,70000000,270000000,96080000
2,2,2022-04,2850000000,1240000000,1209600000,978000000,261600000,120800000,23200000,890000000,385000000,136080000
3,3,2022-05,3120000000,1392000000,1629600000,1320800000,389400000,165600000,51500000,900000000,465000000,182000000
4,4,2022-06,3255000000,1480000000,1887600000,1490400000,474000000,196800000,64100000,900000000,520000000,208160000

In [8]:
tweets = pd.read_csv('../data/Tweets/tweets.csv', dtype=object)
tweets.head()

,Tweet Id,Tweet URL,Tweet Posted Time,Tweet Content,Tweet Type,Client,Retweets Received,Likes Received,Tweet Location,Tweet Language,User Id,Name,Username,User Bio,Verified or Non-Verified,Profile URL,User Followers,User Following,User Account Creation Date
0,"""1562659745852321793""",https://twitter.com/zur_hausen/status/15626597...,25 Aug 2022 04:34:50,"""Kann mir mal jemand erklären, warum junge, we...",ReTweet,"""Twitter for iPhone""",0,0,"""""",German,"""1251901660563210240""","""namenlos""",zur_hausen,"""""",Non-Verified,https://twitter.com/zur_hausen,542,853,19-Apr-2020 15:53:27
1,"""1562659689422520321""",https://twitter.com/MuluTes96885364/status/156...,25 Aug 2022 04:34:37,"""#TigrayUnderAttack \n#StopWarOnTigray \n#Ukra...",ReTweet,"""Twitter for Android""",0,0,"""""",qht,"""1505161753348423682""","""➠ሙሉ አማሃ (ጋል 70እንደርታ መቀለ💊❤)""",MuluTes96885364,"""✍️ሁውከት እና ራብሻ: አብዝበዝሖ ዓለም :እንታይ ነይርዎ ሰላም ብካሴት...",Non-Verified,https://twitter.com/MuluTes96885364,1823,793,19-Mar-2022 12:38:43
2,"""1562659549735034880""",https://twitter.com/Iness054193682/status/1562...,25 Aug 2022 04:34:04,"""Zelensky: “Un attacco missilistico russo cont...",ReTweet,"""Twitter for Android""",0,0,"""""",Italian,"""1505635796187033605""","""Iness""",Iness054193682,"""""",Non-Verified,https://twitter.com/Iness054193682,11,150,20-Mar-2022 20:02:20
3,"""1562659177167593474""",https://twitter.com/koolkustmer/status/1562659...,25 Aug 2022 04:32:35,"""Russia so Engaged in Ukrainian War, America b...",Tweet,"""Twitter for Android""",0,0,"""""",English,"""232279531""","""Andy Khan 🦅🐘""",koolkustmer,"""What you perceive is your reality, what I per...",Non-Verified,https://twitter.com/koolkustmer,635,528,30-Dec-2010 18:32:07
4,"""1562659176966651906""",https://twitter.com/Tsrha_Kw/status/1562659176...,25 Aug 2022 04:32:35,"""#TigrayUnderAttack \n#StopWarOnTigray \n#Ukra...",ReTweet,"""Twitter for Android""",0,0,"""""",qht,"""1485679567570358274""","""Tsrha""",Tsrha_Kw,"""The greatest glory in living lies not in neve...",Non-Verified,https://twitter.com/Tsrha_Kw,1752,703,24-Jan-2022 18:23:28